server:
  port: 3500

spring:
  datasource:
    url: jdbc:mysql://db:3306/my_database?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://db:3306/my_database?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    platform: mysql
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true # true for demo
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100