version: '3.1'

services:
  db:
    image: mysql:8.0.17
    container_name: db
    command: [ '--default-authentication-plugin=mysql_native_password', '--default-storage-engine=innodb' ]
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=my_database
    ports:
      - 3306:3306

  account-service:
    build:
      context: ../../account-service
      dockerfile: Dockerfile
    image: account-service
    hostname: account-service
    container_name: account-service
    volumes:
      - ./account-service.yaml:/application/account-service.yaml
    environment:
      # provide environment properties
      # - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/my_database?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      - SPRING_CONFIG_LOCATION=/application/account-service.yaml
    ports:
      - 3000:3000
    restart: always

    depends_on:
      - db