server:
  port: 3000

logging:
  level:
    root: info
    org.hibernate.SQL: info

spring:
  datasource:
    url: jdbc:h2:mem:testdb?DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb?DB_CLOSE_ON_EXIT=FALSE
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

---

spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/my_database?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/my_database?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    platform: mysql
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100