server:
  port: 3200

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
    registerWithEureka: false